baseURL = 'https://reststop.yenslife.top/'
languageCode = 'zh-TW'
title = '狸開地球前的休息站'
theme = 'story'
hasCJKLanguage = true

[pagination]
  pagerSize = 5

[params]
  summaryLength = 40
  description = "地球是不完美的，但在離開之前，先休息一下吧。"
  ogImage = "/images/beaver-master-story-banner.png"
