baseURL = 'https://stories.yenslife.top/'
languageCode = 'zh-TW'
title = '海狸大師說故事'
theme = 'story'
hasCJKLanguage = true

[pagination]
  pagerSize = 5

[params]
  summaryLength = 40
  description = "在這裡，您可以找到各種溫暖人心的短篇故事。讓文字帶您進入不同的世界."
  ogImage = "/images/beaver-master-story-banner.png"
